// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelExport(arg1, arg2) {
  return window['go']['main']['App']['CancelExport'](arg1, arg2);
}

export function CancelImport(arg1, arg2) {
  return window['go']['main']['App']['CancelImport'](arg1, arg2);
}

export function CancelOperation(arg1, arg2) {
  return window['go']['main']['App']['CancelOperation'](arg1, arg2);
}

export function CancelQuery(arg1, arg2) {
  return window['go']['main']['App']['CancelQuery'](arg1, arg2);
}

export function CleanupExport(arg1, arg2) {
  return window['go']['main']['App']['CleanupExport'](arg1, arg2);
}

export function CleanupImport(arg1, arg2) {
  return window['go']['main']['App']['CleanupImport'](arg1, arg2);
}

export function CloseConnection(arg1) {
  return window['go']['main']['App']['CloseConnection'](arg1);
}

export function CloseQuery(arg1, arg2) {
  return window['go']['main']['App']['CloseQuery'](arg1, arg2);
}

export function DeleteProfile(arg1, arg2) {
  return window['go']['main']['App']['DeleteProfile'](arg1, arg2);
}

export function ExecuteMutation(arg1, arg2) {
  return window['go']['main']['App']['ExecuteMutation'](arg1, arg2);
}

export function GetConnectionState(arg1) {
  return window['go']['main']['App']['GetConnectionState'](arg1);
}

export function GetExportJob(arg1) {
  return window['go']['main']['App']['GetExportJob'](arg1);
}

export function GetImportJob(arg1) {
  return window['go']['main']['App']['GetImportJob'](arg1);
}

export function GetMeasurementSchema(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetMeasurementSchema'](arg1, arg2, arg3);
}

export function GetOperation(arg1) {
  return window['go']['main']['App']['GetOperation'](arg1);
}

export function GetProfile(arg1) {
  return window['go']['main']['App']['GetProfile'](arg1);
}

export function GetProtectionState(arg1) {
  return window['go']['main']['App']['GetProtectionState'](arg1);
}

export function GetQuerySession(arg1) {
  return window['go']['main']['App']['GetQuerySession'](arg1);
}

export function GetResultPage(arg1) {
  return window['go']['main']['App']['GetResultPage'](arg1);
}

export function GetRuntimeStatus() {
  return window['go']['main']['App']['GetRuntimeStatus']();
}

export function GetSchemaSnapshot(arg1) {
  return window['go']['main']['App']['GetSchemaSnapshot'](arg1);
}

export function GetTaskChanges(arg1, arg2) {
  return window['go']['main']['App']['GetTaskChanges'](arg1, arg2);
}

export function GetTaskEventHead() {
  return window['go']['main']['App']['GetTaskEventHead']();
}

export function GetTransientIssue(arg1) {
  return window['go']['main']['App']['GetTransientIssue'](arg1);
}

export function InspectImportSource(arg1) {
  return window['go']['main']['App']['InspectImportSource'](arg1);
}

export function ListExports(arg1) {
  return window['go']['main']['App']['ListExports'](arg1);
}

export function ListOperations(arg1) {
  return window['go']['main']['App']['ListOperations'](arg1);
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function ListQuerySessions() {
  return window['go']['main']['App']['ListQuerySessions']();
}

export function ListRecoverableImports(arg1, arg2) {
  return window['go']['main']['App']['ListRecoverableImports'](arg1, arg2);
}

export function ListResultSeries(arg1, arg2) {
  return window['go']['main']['App']['ListResultSeries'](arg1, arg2);
}

export function LockProtection(arg1) {
  return window['go']['main']['App']['LockProtection'](arg1);
}

export function OpenConnection(arg1) {
  return window['go']['main']['App']['OpenConnection'](arg1);
}

export function PreflightImport(arg1) {
  return window['go']['main']['App']['PreflightImport'](arg1);
}

export function PreviewImportRun(arg1, arg2) {
  return window['go']['main']['App']['PreviewImportRun'](arg1, arg2);
}

export function PreviewMutation(arg1, arg2) {
  return window['go']['main']['App']['PreviewMutation'](arg1, arg2);
}

export function ResolveImportBatch(arg1, arg2) {
  return window['go']['main']['App']['ResolveImportBatch'](arg1, arg2);
}

export function RestartExport(arg1, arg2) {
  return window['go']['main']['App']['RestartExport'](arg1, arg2);
}

export function ResumeImport(arg1, arg2) {
  return window['go']['main']['App']['ResumeImport'](arg1, arg2);
}

export function RunImportNext(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RunImportNext'](arg1, arg2, arg3, arg4);
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}

export function SelectExportDirectory() {
  return window['go']['main']['App']['SelectExportDirectory']();
}

export function SelectImportSource() {
  return window['go']['main']['App']['SelectImportSource']();
}

export function StartExport(arg1) {
  return window['go']['main']['App']['StartExport'](arg1);
}

export function StartImport(arg1, arg2) {
  return window['go']['main']['App']['StartImport'](arg1, arg2);
}

export function StartReadQuery(arg1) {
  return window['go']['main']['App']['StartReadQuery'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function TestSavedConnection(arg1) {
  return window['go']['main']['App']['TestSavedConnection'](arg1);
}

export function UnlockProtection(arg1) {
  return window['go']['main']['App']['UnlockProtection'](arg1);
}
