// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {exportjob} from '../models';
import {transfer} from '../models';
import {operation} from '../models';
import {query} from '../models';
import {main} from '../models';
import {connection} from '../models';
import {protection} from '../models';
import {tasks} from '../models';
import {importworker} from '../models';

export function CancelExport(arg1:string,arg2:exportjob.CommandEnvelope):Promise<exportjob.Job>;

export function CancelImport(arg1:string,arg2:transfer.ImportCommandEnvelope):Promise<transfer.ImportJob>;

export function CancelOperation(arg1:string,arg2:operation.CommandEnvelope):Promise<operation.Operation>;

export function CancelQuery(arg1:string,arg2:query.CommandEnvelope):Promise<query.QuerySession>;

export function CleanupExport(arg1:string,arg2:exportjob.CommandEnvelope):Promise<exportjob.Job>;

export function CleanupImport(arg1:string,arg2:transfer.ImportCommandEnvelope):Promise<transfer.ImportJob>;

export function CloseConnection(arg1:string):Promise<void>;

export function CloseQuery(arg1:string,arg2:query.CommandEnvelope):Promise<query.QuerySession>;

export function DeleteProfile(arg1:string,arg2:string):Promise<void>;

export function ExecuteMutation(arg1:string,arg2:operation.ExecuteRequest):Promise<operation.Operation>;

export function ExportQueryResultCSV(arg1:main.ExportQueryResultInput):Promise<main.QueryResultExportView>;

export function GetConnectionState(arg1:string):Promise<connection.Snapshot>;

export function GetExportJob(arg1:string):Promise<exportjob.Job>;

export function GetImportJob(arg1:string):Promise<transfer.ImportJob>;

export function GetMeasurementSchema(arg1:string,arg2:string,arg3:string):Promise<main.SchemaMeasurement>;

export function GetOperation(arg1:string):Promise<operation.Operation>;

export function GetProfile(arg1:string):Promise<main.ProfileView>;

export function GetProtectionState(arg1:string):Promise<protection.Snapshot>;

export function GetQuerySession(arg1:string):Promise<query.QuerySession>;

export function GetResultPage(arg1:query.PageRequest):Promise<main.QueryResultPageView>;

export function GetRuntimePlatform():Promise<main.RuntimePlatform>;

export function GetRuntimeStatus():Promise<main.RuntimeStatus>;

export function GetSchemaSnapshot(arg1:string):Promise<Array<main.SchemaDatabase>>;

export function GetTaskChanges(arg1:string,arg2:number):Promise<Array<tasks.Event>>;

export function GetTaskEventHead():Promise<string>;

export function GetTransientIssue(arg1:string):Promise<string>;

export function InspectImportSource(arg1:string):Promise<main.ImportSourceInspection>;

export function ListExports(arg1:exportjob.ListFilter):Promise<Array<exportjob.Job>>;

export function ListOperations(arg1:number):Promise<Array<operation.Operation>>;

export function ListProfiles():Promise<Array<main.ProfileView>>;

export function ListQuerySessions():Promise<Array<query.QuerySession>>;

export function ListRecoverableImports(arg1:string,arg2:number):Promise<Array<transfer.ImportJob>>;

export function ListResultSeries(arg1:string,arg2:number):Promise<Array<query.SeriesSummary>>;

export function LockProtection(arg1:protection.LockRequest):Promise<protection.CommandResult>;

export function OpenConnection(arg1:string):Promise<connection.Snapshot>;

export function PreflightImport(arg1:main.PreflightImportInput):Promise<transfer.PreflightImportResponse>;

export function PreviewImportRun(arg1:string,arg2:transfer.PreviewRunRequest):Promise<transfer.ImportRunPreview>;

export function PreviewMutation(arg1:string,arg2:operation.PreviewRequest):Promise<operation.Preview>;

export function ResolveImportBatch(arg1:string,arg2:transfer.AuthorizedResolveRequest):Promise<transfer.ImportJob>;

export function RestartExport(arg1:string,arg2:exportjob.CommandEnvelope):Promise<exportjob.Job>;

export function ResumeImport(arg1:string,arg2:transfer.AuthorizedStartRequest):Promise<transfer.ImportJob>;

export function RunImportNext(arg1:string,arg2:string,arg3:string,arg4:string):Promise<importworker.Result>;

export function SaveProfile(arg1:main.SaveProfileInput):Promise<main.ProfileView>;

export function SelectExportDirectory():Promise<string>;

export function SelectImportSource():Promise<main.ImportSourceInspection>;

export function StartExport(arg1:main.StartExportInput):Promise<exportjob.Job>;

export function StartImport(arg1:string,arg2:transfer.AuthorizedStartRequest):Promise<transfer.ImportJob>;

export function StartReadQuery(arg1:main.StartReadQueryInput):Promise<query.QuerySession>;

export function TestConnection(arg1:main.TestConnectionInput):Promise<connection.ProbeResult>;

export function TestSavedConnection(arg1:string):Promise<connection.ProbeResult>;

export function UnlockProtection(arg1:protection.UnlockRequest):Promise<protection.CommandResult>;
